default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: note_bot_development

test:
  <<: *default
  database: note_bot_test

production:
  <<: *default
  database: note_bot_production
  username: note_bot
  password: <%= ENV['RAILS_BASE_DATABASE_PASSWORD'] %>
